### PR TITLE
Add an AppVeyor config

### PR DESCRIPTION
**Pull request by Arcanemagus**
Test PR to trigger AppVeyor.

### CODE REVIEW

**Comment by Arcanemagus** [comment]
PS: You might be getting spammed by these builds @olleolleolle, if so I'm sorry :stuck_out_tongue:

**Comment by olleolleolle** [comment]
@Arcanemagus This is super-cool!

To minimise the output, you could use `--no-document` for the `gem` command.

`--no-post-install-message` can also help

**Comment by olleolleolle** [comment]
(Ah, I see that the Pull Request has been pointed not at the main repo, but against master on this one. 

You may be missing a `git remote` in your local checkout.) This may be intentional, of course!

**Comment by Arcanemagus** [comment]
Nope, I purposely pointed it here to test things, will be submitting a PR against the proper repo as soon as it's verified working... which should be any minute now :wink:

I just tagged you here (mistakenly) since the notification email is set to the same as Travis, looking at that though it is probably somebody else :stuck_out_tongue:

**Comment by olleolleolle** [comment]
Bonus round: `gem update --system --no-document --no-post-install-message`

**Comment by olleolleolle** [comment]
:tada:

**Comment by Arcanemagus** [comment]
Okay, making that change and then I'll send it to the right repo.

**Pull request closed without merging**
